### PR TITLE
Case insensitive matching for BankDebitCredit converter

### PR DESCRIPTION
**Pull request by rajabilal555**
A simple change.

Changes in this pull request:

The converter for BankDebitCredit can now match case insensitively.
Solved the problem of some exports having 'Dr' instead of 'DR', and all transactions getting passed as Credits

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Looks pretty good! But why map a static array? Why not make it lowercase by default?

**Comment by rajabilal555** [comment]
Honestly. It was just least lines changed, and so less chances of a mistake. Also in case if someone adds a new option in future and didn't realize the array should be all lowercased. Also seemed more logically followable.

**Comment by JC5** [comment]
That can always be mended by adding a little instruction to the comments, and new PRs are vetted anyway. 

If you would be so kind.

**Comment by rajabilal555** [comment]
I have amended my commit. You can take a look @JC5.

**Comment by JC5** [comment]
Nice, thanks!

**Pull request merged**
