### PR TITLE
Missing creditor name

### PR DESCRIPTION
**Pull request by Fgruntjes**
Fixes issue where `creditorName` is empty in Nordigen transactions. This results in "(unknown destination account)" transactions. For example with:

```json
{
  "bookingDate": "2021-12-15",
  "debtorAccount": {
    "iban": "BEXXXXXX"
  },
  "debtorName": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "proprietaryBankTransactionCode": "247",
  "remittanceInformationUnstructuredArray": [
    "SEPA Incasso algemeen doorlopend",
    "Incassant: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "Naam: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "Machtiging: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "Omschrijving: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1",
    "IBAN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "Kenmerk: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  ],
  "transactionAmount": {
    "amount": "-92",
    "currency": "EUR"
  },
  "transactionId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

Changes in this pull request:
- The Nordigen transactions will fall back to `debtorName`/`debtorAccountIban` when `creditorName`/`creditorAccountIban` is empty.

Not sure if this is the way to go, please let me know if I should change anything.

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
The debtor name should never be the destination, that's where the money comes from.

**Comment by JC5** [comment]
Please send me the following info over email (james@firefly-iii.org)

- uncensored transaction
- account ID (from your JSON config)
- bank name

Thanks in advance!

**Comment by Fgruntjes** [comment]
> Please send me the following info over email ([james@firefly-iii.org](mailto:james@firefly-iii.org))
> 
> * uncensored transaction
> * account ID (from your JSON config)
> * bank name

Done

**Comment by scottgrobinson** [comment]
How would I get the above information for you? I don't see that in my importer logs (with debug on). I appear to have a similar issue. A large amount of my transactions have (unknown source account)

**Comment by JC5** [comment]
The logs report the top two items and I assume you know the third one.

**Comment by scottgrobinson** [comment]
OK - Mine is even "worse", appologies. "Slightly" different issue for me the data isn't even there..... (Bank - Lloyds UK)

```
{
   "bookingDate":"2021-10-06",
   "proprietaryBankTransactionCode":"BP",
   "remittanceInformationUnstructured":"SAVETHECHANGE-3568",
   "transactionAmount":{
      "amount":"0.32",
      "currency":"GBP"
   },
   "transactionId":"T1fc7873846625d221f74a9e4cdd5b671",
   "valueDate":"2021-10-06",
   "key":"booked"
}
```

**Comment by JC5** [comment]
If there is no opposing account information, there's not much I can do. Sorry about that, @scottgrobinson.

Regarding the original issue @Fgruntjes, i have not heard back from Nordigen yet.

**Comment by JC5** [comment]
Addendum: you can make rules based on the description: if description contains `this` then set the destination account to `that`.

**Comment by safriks** [comment]
Hi, Nordigen here (i havent updated my profile in a long time)

we already have a pull request for this, it will likely be on prod next week
will ping @JC5 when that is the case

big thanks for reporting issues like this <3
do keep at it and we will be there for you!

**Comment by JC5** [comment]
This PR can be closed, as the fix is now live. Thanks, everybody.

**Pull request closed without merging**
